import { useMemo, useState } from 'react';
import { FlatList, Pressable, Text, View } from 'react-native';
import { AppScreen } from '../../components/AppScreen';
import { EmptyState } from '../../components/EmptyState';
import { GlassCard } from '../../components/GlassCard';
import { MotionView } from '../../components/MotionView';
import { ScreenHeader } from '../../components/ScreenHeader';
import { useDecisions } from '../../hooks/useDecisions';
import { DecisionAction } from '../../types';

const actions: Array<DecisionAction | 'ALL'> = ['ALL', 'BUY', 'SELL', 'HOLD'];

const shortTxId = (txId: string) => `${txId.slice(0, 6)}...${txId.slice(-6)}`;

const ACTION_CONFIG: Record<DecisionAction, { color: string; bg: string; label: string }> = {
  BUY:  { color: '#10B981', bg: '#ECFDF5', label: '↑ BUY'  },
  SELL: { color: '#F43F5E', bg: '#FFF1F2', label: '↓ SELL' },
  HOLD: { color: '#F59E0B', bg: '#FFFBEB', label: '◆ HOLD' },
};

const ACCENT: Record<DecisionAction, 'emerald' | 'rose' | 'amber'> = {
  BUY: 'emerald',
  SELL: 'rose',
  HOLD: 'amber',
};

export function AILogScreen() {
  const { data, isLoading, refetch } = useDecisions();
  const [filter, setFilter] = useState<DecisionAction | 'ALL'>('ALL');
  const [newestFirst, setNewestFirst] = useState(true);

  const list = useMemo(() => {
    const base = data ?? [];
    const filtered = filter === 'ALL' ? base : base.filter((item) => item.action === filter);
    return [...filtered].sort((a, b) => {
      const aTime = new Date(a.timestamp).getTime();
      const bTime = new Date(b.timestamp).getTime();
      return newestFirst ? bTime - aTime : aTime - bTime;
    });
  }, [data, filter, newestFirst]);

  return (
    <AppScreen>
      <MotionView delay={40}>
        <ScreenHeader
          eyebrow="history"
          title="AI Decision Log"
          subtitle="All trading signals generated by the AI agent."
        />
      </MotionView>

      {/* Filter pills */}
      <MotionView delay={100}>
        <View style={{ flexDirection: 'row', gap: 8, marginBottom: 12 }}>
          {actions.map((action) => {
            const isActive = filter === action;
            const cfg = action !== 'ALL' ? ACTION_CONFIG[action] : null;
            return (
              <Pressable
                key={action}
                onPress={() => setFilter(action)}
                style={{
                  paddingHorizontal: 14,
                  paddingVertical: 7,
                  borderRadius: 20,
                  backgroundColor: isActive ? (cfg?.color ?? '#111111') : '#F3F4F6',
                  borderWidth: 1,
                  borderColor: isActive ? (cfg?.color ?? '#111111') : '#E5E7EB',
                }}
              >
                <Text style={{ fontSize: 12, fontWeight: '700', color: isActive ? '#FFFFFF' : '#6B7280' }}>
                  {action}
                </Text>
              </Pressable>
            );
          })}

          <Pressable
            onPress={() => setNewestFirst((prev) => !prev)}
            style={{
              marginLeft: 'auto',
              paddingHorizontal: 12,
              paddingVertical: 7,
              borderRadius: 20,
              backgroundColor: '#F3F4F6',
              borderWidth: 1,
              borderColor: '#E5E7EB',
            }}
          >
            <Text style={{ fontSize: 11, fontWeight: '600', color: '#6B7280' }}>
              {newestFirst ? '↓ Newest' : '↑ Oldest'}
            </Text>
          </Pressable>
        </View>
      </MotionView>

      <FlatList
        data={list}
        keyExtractor={(item) => item.id}
        refreshing={isLoading}
        onRefresh={refetch}
        showsVerticalScrollIndicator={false}
        contentContainerStyle={{ paddingBottom: 20 }}
        ListEmptyComponent={<EmptyState title="No decisions yet" subtitle="AI signals will appear here." />}
        renderItem={({ item, index }) => {
          const cfg = ACTION_CONFIG[item.action];
          return (
            <MotionView delay={120 + index * 30}>
              <GlassCard accent={ACCENT[item.action]}>
                {/* Header row */}
                <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 }}>
                  <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                    <View style={{ backgroundColor: cfg.bg, borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4 }}>
                      <Text style={{ fontSize: 12, fontWeight: '800', color: cfg.color, letterSpacing: 0.5 }}>
                        {cfg.label}
                      </Text>
                    </View>
                    <Text style={{ fontSize: 12, color: '#9CA3AF' }}>
                      {new Date(item.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </Text>
                  </View>
                  {/* Confidence */}
                  <View style={{ alignItems: 'flex-end' }}>
                    <Text style={{ fontSize: 18, fontWeight: '800', color: cfg.color }}>
                      {item.confidence}%
                    </Text>
                    <Text style={{ fontSize: 10, color: '#9CA3AF' }}>confidence</Text>
                  </View>
                </View>

                {/* Confidence bar */}
                <View style={{ height: 3, backgroundColor: '#F3F4F6', borderRadius: 2, marginBottom: 10 }}>
                  <View style={{ height: 3, width: `${item.confidence}%`, backgroundColor: cfg.color, borderRadius: 2 }} />
                </View>

                {/* Explanation */}
                <Text style={{ fontSize: 13, color: '#374151', lineHeight: 19, marginBottom: 10 }}>
                  {item.explanation}
                </Text>

                {/* Footer */}
                <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}>
                  <Text style={{ fontSize: 13, fontWeight: '700', color: '#111111' }}>
                    SOL ${item.price.toFixed(2)}
                  </Text>
                  <Text style={{ fontSize: 11, color: '#D1D5DB', fontFamily: 'monospace' }}>
                    {shortTxId(item.txId)}
                  </Text>
                </View>
              </GlassCard>
            </MotionView>
          );
        }}
      />
    </AppScreen>
  );
}
